name: PullRequest Contributor Welcome

on:
  pull_request_target:
    types:
      - closed
#    paths:
#      - 'components/**'

permissions:
  contents: read

jobs:
  comment:
    permissions:
      issues: write  # for actions-cool/maintain-one-comment to modify or create issue comments
      pull-requests: write  # for actions-cool/maintain-one-comment to modify or create PR comments
    if: github.event.pull_request.merged == true && github.repository == 'vue-blocks/vue-blocks'
    runs-on: ubuntu-latest
    steps:
      - name: get commit count
        id: get_commit_count
        run: |
          PR_AUTHOR=$(echo "${{ github.event.pull_request.user.login }}")
          RESULT_DATA=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits?author=${PR_AUTHOR}&per_page=5")
          DATA_LENGTH=$(echo $RESULT_DATA | jq 'if type == "array" then length else 0 end')
          echo "COUNT=$DATA_LENGTH" >> $GITHUB_OUTPUT
      - name: Comment on PR
        if: steps.get_commit_count.outputs.COUNT < 10
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🎉 Thank you for your contribution

            <!-- WELCOME_CONTRIBUTION -->
          body-include: <!-- WELCOME_CONTRIBUTION -->
